### ISSUE TITLE
Asynchronous Handlers?

### ISSUE THREAD

**Issue by newlegendmedia** [azasypkin/event-dispatcher#4]
In emit(), this object calls any registered handlers. Are those calls asynchronous or does it wait for each one to complete?

**Comment by azasypkin** [comment]
`emit` is synchronous and [runs handlers one by one waiting for each one to complete](https://github.com/azasypkin/event-dispatcher/blob/master/src/event-dispatcher.js#L141-L147).

**Comment by azasypkin** [comment]
I'm closing this one, let me know if you have any other questions @newlegendmedia
